services:
  distributor:
    build:
      context: .
      dockerfile: distributor/Dockerfile
    environment:
      - ANALYZERS_JSON=[{"id":"a1","url":"http://analyzer1:9000/ingest","weight":0.1},{"id":"a2","url":"http://analyzer2:9000/ingest","weight":0.4},{"id":"a3","url":"http://analyzer3:9000/ingest","weight":0.2},{"id":"a4","url":"http://analyzer4:9000/ingest","weight":0.3}]
      - EMITTERS_JSON=[{"emitter_id":"emit1","url":"http://emitter1:9100"},{"emitter_id":"emit2","url":"http://emitter2:9100"},{"emitter_id":"emit3","url":"http://emitter3:9100"},{"emitter_id":"emit4","url":"http://emitter4:9100"}]
    ports:
      - "8000:8000"

  analyzer1:
    build: ./analyzers
    expose: ["9000"]

  analyzer2:
    build: ./analyzers
    expose: ["9000"]

  analyzer3:
    build: ./analyzers
    expose: ["9000"]

  analyzer4:
    build: ./analyzers
    expose: ["9000"]

  emitter1:
    build: ./emitters
    environment:
      - DISTRIBUTOR_URL=http://distributor:8000/log-packet
      - EMITTER_ID=emit1
      - RATE_RPS=1
    expose: ["9100"]
    depends_on: [distributor]

  emitter2:
    build: ./emitters
    environment:
      - DISTRIBUTOR_URL=http://distributor:8000/log-packet
      - EMITTER_ID=emit2
      - RATE_RPS=1
    expose: ["9100"]
    depends_on: [distributor]

  emitter3:
      build: ./emitters
      environment:
        - DISTRIBUTOR_URL=http://distributor:8000/log-packet
        - EMITTER_ID=emit3
        - RATE_RPS=1
      expose: ["9100"]
      depends_on: [distributor]

  emitter4:
      build: ./emitters
      environment:
        - DISTRIBUTOR_URL=http://distributor:8000/log-packet
        - EMITTER_ID=emit4
        - RATE_RPS=1
      expose: ["9100"]
      depends_on: [distributor]
