services:
  distributor:
    build: ./distributor
    environment:
      - ANALYZERS_JSON=[{"id":"a1","url":"http://analyzer1:9000/ingest","weight":0.6},{"id":"a2","url":"http://analyzer2:9000/ingest","weight":0.4}]
    ports:
      - "8000:8000"

  analyzer1:
    build: ./analyzers
    expose: ["9000"]

  analyzer2:
    build: ./analyzers
    expose: ["9000"]

  emitter1:
    build: ./emitters
    environment:
      - DISTRIBUTOR_URL=http://distributor:8000/log-packet
      - EMITTER_ID=emit1
      - RATE_RPS=4
    ports:
      - "9101:9100"      # control via localhost:9101
    depends_on: [distributor]

  emitter2:
    build: ./emitters
    environment:
      - DISTRIBUTOR_URL=http://distributor:8000/log-packet
      - EMITTER_ID=emit2
      - RATE_RPS=2
    ports:
      - "9102:9100"
    depends_on: [distributor]
